/**
 * Mapping of local asset paths (conceptual) to Cloudinary Public IDs.
 * Generated automatically from cloudinary_links.txt.
 */
export const ASSET_MAP = {
    "videos/CA1.mp4": "CA1_lg4nfo.mp4",
    "videos/CA3.mp4": "CA3_s3jr29.mp4",
    "videos/CA2.mp4": "CA2_xo8ntk.mp4",
    "videos/M1_C.mp4": "M1_C_gvixge.mp4",
    "videos/Hyatt_3.mp4": "Hyatt_3_vhdfcf.mp4",
    "videos/W1.mp4": "W1_vktt2g.mp4",
    "videos/Hyatt_2.mp4": "Hyatt_2_f7rka5.mp4",
    "videos/M2_c.mp4": "M2_c_rirclg.mp4",
    "videos/Hyatt_1.mp4": "Hyatt_1_ixgerz.mp4",
    "videos/W3.mp4": "W3_x2n7xq.mp4",
    "videos/W2.mp4": "W2_b9qhcl.mp4",
    "assets/amit/3.jpg": "3_imsnue.jpg",
    "assets/amit/1.jpg": "1_ky5uqm.jpg",
    "assets/amit/5.jpg": "5_ghdbff.jpg",
    "assets/amit/4.jpg": "4_sjvc8c.jpg",
    "assets/amit/2.jpg": "2_wg7ryj.jpg",
    "assets/falguni/5.jpg": "5_n2acxy.jpg",
    "assets/falguni/1.jpg": "1_b1agas.jpg",
    "assets/falguni/4.jpg": "4_m7o7ng.jpg",
    "assets/falguni/2.jpg": "2_aq4iaf.jpg",
    "assets/falguni/3.jpg": "3_xmjszf.jpg",
    "assets/personal/p_7.jpg": "p_7_yfi7o3.jpg",
    "assets/personal/p_6.jpg": "p_6_k1ahmg.jpg",
    "assets/personal/p_5.jpg": "p_5_gbx481.jpg",
    "assets/personal/p_3.jpg": "p_3_iocyv9.jpg",
    "assets/personal/p_4.jpg": "p_4_arn6el.jpg",
    "assets/salim/3.jpg": "3_keuqse.jpg",
    "assets/salim/5.heic": "5_aa8qqh.heic",
    "assets/salim/4.jpg": "4_nd9nxx.jpg",
    "assets/salim/2.jpg": "2_xi3asl.jpg",
    "assets/salim/1.jpg": "1_m5cevj.jpg",
    "assets/sanam/5.jpg": "5_sk2bwe.jpg",
    "assets/sanam/4.jpg": "4_witsga.jpg",
    "assets/sanam/1.jpg": "1_tza2xd.jpg",
    "assets/sanam/3.jpg": "3_uzwtq6.jpg",
    "assets/sanam/2.jpg": "2_b1o6xj.jpg",
    "thumbnails/W3.png": "W3_an8zu7.png",
    "thumbnails/W2.png": "W2_pqgw02.png",
    "thumbnails/M2.png": "M2_uo2ceh.png",
    "thumbnails/W1.png": "W1_qzqtk7.png",
    "thumbnails/M1.png": "M1_gabtht.png",
    "thumbnails/Hyatt_3.png": "Hyatt_3_cmsaq7.png",
    "thumbnails/Hyatt_2.png": "Hyatt_2_nwdegm.png",
    "thumbnails/CA3.png": "CA3_nsn5b2.png",
    "thumbnails/Hyatt_1.png": "Hyatt_1_vfzml0.png",
    "thumbnails/CA1.png": "CA1_pgpcu0.png",
    "thumbnails/CA2.png": "CA2_grnrh3.png",
    "whitford_grid/g4_2.png": "g4_2_ngrccz.png",
    "whitford_grid/g9_1.png": "g9_1_xtvx00.png",
    "whitford_grid/g7_1.png": "g7_1_xcyjj8.png",
    "whitford_grid/g9_3.png": "g9_3_umgdp8.png",
    "whitford_grid/g9_2.png": "g9_2_pzhdx7.png",
    "whitford_grid/g5_4.png": "g5_4_rjjogb.png",
    "whitford_grid/g9_3.jpg": "g9_3_xxgl9o.jpg",
    "whitford_grid/g9_2.jpg": "g9_2_ibyswl.jpg",
    "whitford_grid/g8_3.png": "g8_3_xklxl1.png",
    "whitford_grid/g9_1.jpg": "g9_1_efznfv.jpg",
    "whitford_grid/g8_2.png": "g8_2_x3k37a.png",
    "whitford_grid/g8_3.jpg": "g8_3_sqote6.jpg",
    "whitford_grid/g8_1.png": "g8_1_tjeiiw.png",
    "whitford_grid/g7_3.png": "g7_3_zycpvh.png",
    "whitford_grid/g8_2.jpg": "g8_2_zo5zgt.jpg",
    "whitford_grid/g7_2.png": "g7_2_js4qw5.png",
    "whitford_grid/g8_1.jpg": "g8_1_omh7to.jpg",
    "whitford_grid/g7_3.jpg": "g7_3_p9dkf4.jpg",
    "whitford_grid/g6_1.png": "g6_1_nzkkod.png",
    "whitford_grid/g2_3.png": "g2_3_sfpnr6.png",
    "whitford_grid/g7_2.jpg": "g7_2_y8nt0r.jpg",
    "whitford_grid/g6_3.png": "g6_3_ewvgl5.png",
    "whitford_grid/g7_1.jpg": "g7_1_hwyx1s.jpg",
    "whitford_grid/g6_2.png": "g6_2_yfmf0z.png",
    "whitford_grid/g6_3.jpg": "g6_3_vsdpjo.jpg",
    "whitford_grid/g4_1.png": "g4_1_fvygc9.png",
    "whitford_grid/g6_2.jpg": "g6_2_uy34z1.jpg",
    "whitford_grid/g5_2.png": "g5_2_bcpjqc.png",
    "whitford_grid/g6_1.jpg": "g6_1_dpbume.jpg",
    "whitford_grid/g5_3.png": "g5_3_vgxbz9.png",
    "whitford_grid/g5_4.jpg": "g5_4_udn0ag.jpg",
    "whitford_grid/g2_2.png": "g2_2_orb1ch.png",
    "whitford_grid/g5_3.jpg": "g5_3_hvrkw7.jpg",
    "whitford_grid/g5_1.png": "g5_1_wlbxft.png",
    "whitford_grid/g5_2.jpg": "g5_2_oyl8ga.jpg",
    "whitford_grid/g4_3.png": "g4_3_hi08qb.png",
    "whitford_grid/g5_1.jpg": "g5_1_wv99ff.jpg",
    "whitford_grid/g1_2.png": "g1_2_l4hy3y.png",
    "whitford_grid/g4_3.jpg": "g4_3_builda.jpg",
    "whitford_grid/g1_1.png": "g1_1_fww5p3.png",
    "whitford_grid/g4_2.jpg": "g4_2_vv43aj.jpg",
    "whitford_grid/g4_1.jpg": "g4_1_xcra3i.jpg",
    "whitford_grid/g3_2.png": "g3_2_wmk51p.png",
    "whitford_grid/g2_1.png": "g2_1_orrxkx.png",
    "whitford_grid/g3_2.jpg": "g3_2_rqx7pb.jpg",
    "whitford_grid/g3_1.png": "g3_1_l1c8xu.png",
    "whitford_grid/g2_3.jpg": "g2_3_b5dmsg.jpg",
    "whitford_grid/g1_2.jpg": "g1_2_ibaiyd.jpg",
    "whitford_grid/g2_2.jpg": "g2_2_emcckk.jpg",
    "whitford_grid/g1_1.jpg": "g1_1_ybi8hd.jpg",
    "whitford_grid/g2_1.jpg": "g2_1_tiepzc.jpg"
};

export const getAssetPath = (path) => {
    // Navigate path: e.g. "/whitford_grid/g1_1.jpg" -> "whitford_grid/g1_1.jpg"
    // Remove leading slash if present
    const cleanPath = path.startsWith('/') ? path.slice(1) : path;
    // Try exact match
    if (ASSET_MAP[cleanPath]) return ASSET_MAP[cleanPath];
    
    // Try matching without leading assets/ if fails
    // (e.g. if code requests "personal/p_1.jpg" but key is "assets/personal/p_1.jpg" OR vice versa)
    // Actually, let's just stick to exact match first.
    
    return null;
};
